/**
 * Vendored from KaTeX (MIT) — see KATEX_LICENSE in this directory.
 * The file itself is GENERATED by KaTeX's buildMetrics.sh; do not edit by hand.
 *
 * Each glyph metric is a tuple `[depth, height, italic, skew, width]` in em
 * units (font size = 1), keyed by Unicode codepoint within a font variant.
 */
export type CharacterMetricsTuple = [
  depth: number,
  height: number,
  italic: number,
  skew: number,
  width: number,
];

type FontMetrics = Record<number, CharacterMetricsTuple>;

declare const fontMetricsData: Record<string, FontMetrics>;

export default fontMetricsData;
