import type { Script } from "@tasfer/spell";
import { publicAssetUrl } from "@/lib/publicAssetUrl";
import catalog from "./catalog.json";
import type { ImportedDictionary } from "./userDictionaries";

/**
 * A dictionary the app can load into the spell worker.
 *
 * `source` paths are public-asset paths (relative to the app's base URL), never
 * absolute URLs: the same descriptor must resolve on the web (`/app/spell/…`),
 * in Electron's `file://` renderer and under Capacitor's `https://tasfer.app`
 * origin, so callers go through {@link dictionaryUrls}. A bundled dictionary's
 * `id` is its BCP-47 tag and {@link makeDictionaryNamer} turns it into a name;
 * a dictionary imported on this device carries the `label` the person typed
 * and reads its bytes from the `UserDictionaryStore` instead.
 */
export interface DictionaryDescriptor {
  /** Dictionary id — doubles as the `lang` sent to the worker. */
  id: string;
  lang: string;
  script: Script;
  /** A name the person typed (imported dictionaries only); shown as written. */
  label?: string;
  /** Uncompressed bytes on disk (what the cache holds). */
  sizeBytes: number;
  /** Approximate compressed bytes on the wire (what a first enable downloads). */
  wireSizeBytes: number;
  /** SPDX expression of the option Tasfer distributes the dictionary under. */
  license?: string;
  source:
    | {
        /** Bytes committed under `public/app/spell/<id>/` — in every bundle. */
        kind: "bundled";
        aff: string;
        dic: string;
        extras?: string[];
      }
    | {
        /**
         * Bytes fetched from the npm package that publishes them, over a
         * public CDN. Paths are relative to a {@link SPELL_CATALOG_BASES}
         * entry and pin an exact version, so a URL's content never changes.
         */
        kind: "upstream";
        aff: string;
        dic: string;
      }
    | { kind: "imported"; format: "pair" | "list" };
}

/**
 * Where a catalogue dictionary's files come from, in the order they are tried.
 *
 * Tasfer serves ninety languages without hosting a byte of them: each is
 * fetched from its own npm package, at a pinned version, through a public CDN.
 * Mirroring them would be ~300 MB in every deploy and a native bundle that
 * had to strip it again.
 *
 * Two CDNs rather than one, because this is the only network dependency in an
 * otherwise local-first app and an outage would silently stop new languages
 * from installing. jsDelivr is first: it negotiates brotli (a third of the
 * bytes unpkg sends) and both answer with `Access-Control-Allow-Origin: *` and
 * a one-year immutable cache — which is what lets the Electron and Capacitor
 * shells, which have no service worker, keep a language across launches.
 *
 * `VITE_SPELL_CATALOG_URL` replaces both with one base, for a deployment that
 * would rather serve its own copy than reach a CDN at all.
 */
export const SPELL_CATALOG_BASES: readonly string[] = (() => {
  const override = (import.meta.env as Record<string, string | undefined>)
    .VITE_SPELL_CATALOG_URL;
  const bases = override
    ? [override]
    : ["https://cdn.jsdelivr.net/npm/", "https://unpkg.com/"];
  return bases.map((base) => base.replace(/\/?$/, "/"));
})();

interface CatalogEntry {
  id: string;
  kind: "vendored" | "catalog";
  /** npm package name; catalogue entries only. */
  pkg?: string;
  /** Exact published version, pinned into the URL; catalogue entries only. */
  version?: string;
  license?: string;
  script: string;
  sizeBytes: number;
  wireSizeBytes: number;
}

/**
 * Every dictionary Tasfer offers, from `src/spell/catalog.json` (generated by
 * scripts/gen-spell-catalog.mjs from github.com/wooorm/dictionaries).
 *
 * The list is committed rather than fetched because "Add languages" must show
 * it before a byte is downloaded, offline and on every platform; only the
 * dictionary itself needs the network, and only once per device. `en` and `ar`
 * are vendored in the repository under `public/app/spell/<id>/` and are in
 * every bundle, so a cold offline install still checks them.
 *
 * Their notices are reproduced in THIRD-PARTY-LICENSES.txt by
 * scripts/gen-third-party-licenses.mjs.
 */
export const BUNDLED_DICTIONARIES: DictionaryDescriptor[] = (
  catalog.dictionaries as CatalogEntry[]
).map((entry) => ({
  id: entry.id,
  lang: entry.id,
  script: entry.script as Script,
  sizeBytes: entry.sizeBytes,
  wireSizeBytes: entry.wireSizeBytes,
  license: entry.license,
  source:
    entry.kind === "vendored"
      ? {
          kind: "bundled",
          aff: `app/spell/${entry.id}/index.aff.txt`,
          dic: `app/spell/${entry.id}/index.dic.txt`,
        }
      : {
          kind: "upstream",
          aff: `${entry.pkg}@${entry.version}/index.aff`,
          dic: `${entry.pkg}@${entry.version}/index.dic`,
        },
}));

/**
 * Where a descriptor's files can be read from, best first.
 *
 * One list per file rather than one URL: a vendored dictionary resolves to a
 * single asset path in this bundle, while a catalogue one resolves to every
 * CDN in {@link SPELL_CATALOG_BASES}, and the caller tries them in turn.
 */
export function dictionaryUrls(d: DictionaryDescriptor): {
  aff: string[];
  dic: string[];
  extras: string[];
} {
  if (d.source.kind === "imported") {
    throw new Error(`spell: ${d.id} has no downloadable assets`);
  }
  if (d.source.kind === "upstream") {
    const at = (path: string) => SPELL_CATALOG_BASES.map((b) => `${b}${path}`);
    return { aff: at(d.source.aff), dic: at(d.source.dic), extras: [] };
  }
  return {
    aff: [publicAssetUrl(d.source.aff)],
    dic: [publicAssetUrl(d.source.dic)],
    extras: (d.source.extras ?? []).map(publicAssetUrl),
  };
}

/**
 * A dictionary imported on this device, in the shape the service loads.
 * Its bytes come from the `UserDictionaryStore`, never a URL, so there is
 * nothing to download and nothing on the wire.
 */
export function importedDescriptor(
  d: ImportedDictionary,
): DictionaryDescriptor {
  return {
    id: d.id,
    lang: d.lang,
    script: d.script,
    label: d.label,
    sizeBytes: d.bytes,
    wireSizeBytes: 0,
    source: { kind: "imported", format: d.kind },
  };
}

/** The Hunspell WebAssembly binary (copied in by scripts/copy-spell-wasm.mjs). */
export const SPELL_WASM_URL = publicAssetUrl("app/spell/hunspell.wasm");

/**
 * Names a dictionary for display.
 *
 * Bundled dictionaries are BCP-47 tags, so `Intl.DisplayNames` already knows
 * their name in every interface language Tasfer ships — a per-language i18n key
 * per dictionary would only be a worse copy of that table, and would go stale
 * the moment a language is added. A dictionary imported on this device carries
 * the label the person typed and is shown exactly as written.
 *
 * Returns a closure so the (comparatively costly) formatter is built once per
 * render rather than once per row, and never as module state.
 */
export function makeDictionaryNamer(
  uiLocale: string,
): (d: DictionaryDescriptor) => string {
  let display: Intl.DisplayNames | null = null;
  try {
    display = new Intl.DisplayNames([uiLocale], { type: "language" });
  } catch {
    display = null;
  }
  return (d) => {
    if (d.source.kind === "imported") return d.label ?? d.id;
    try {
      const name = display?.of(d.id);
      if (name && name !== d.id) return name;
    } catch {
      // An id Intl cannot parse: fall through to the tag itself.
    }
    return d.id;
  };
}

/**
 * The dictionary's name in its own language ("Deutsch", "العربية") — how
 * someone finds their language when the interface is in one they read poorly.
 * Null when it would only repeat {@link makeDictionaryNamer}'s answer, or for
 * a dictionary imported on this device (its label is already the person's own
 * words).
 */
export function dictionaryEndonym(
  d: DictionaryDescriptor,
  uiLocale: string,
): string | null {
  if (d.source.kind === "imported") return null;
  try {
    const own = new Intl.DisplayNames([d.id], { type: "language" }).of(d.id);
    if (!own || own === d.id) return null;
    const inUi = new Intl.DisplayNames([uiLocale], { type: "language" }).of(
      d.id,
    );
    return own === inUi ? null : own;
  } catch {
    return null;
  }
}

/**
 * The dictionaries to switch on for someone who has never opened these
 * settings: the languages their device says they read, in their own order.
 *
 * Only dictionaries that ship in the bundle are eligible. Nothing may enable
 * itself if turning it on would reach the network — a first launch on a French
 * device must not quietly pull megabytes off a CDN for a choice nobody made,
 * in an app that otherwise never needs one. The catalogue's other languages
 * stay one checkbox away in Settings, and that checkbox is where the person
 * agrees to the download. So the matching runs against the vendored
 * dictionaries alone, and region is dropped to reach one ("en-GB" and "pt-BR"
 * both find their base language, since neither is vendored).
 *
 * `uiLocale` — the language the app itself is running in — is appended, so the
 * language someone picked for the interface is always among the ones being
 * checked. It is skipped when a variant of it is already in the list: a device
 * asking for en-GB has English covered, and a second English dictionary would
 * only be another download saying the same thing.
 *
 * `locales` is `navigator.languages` in the app and an explicit list in tests.
 */
export function preferredLanguages(
  locales: readonly string[],
  catalog: readonly DictionaryDescriptor[],
  uiLocale?: string,
): string[] {
  const ids = catalog
    .filter((d) => d.source.kind === "bundled")
    .map((d) => d.id);
  // Longest match first: a "de-AT" dictionary beats plain "de" for de-AT.
  const match = (tag: string): string | null => {
    const parts = tag.trim().split("-");
    for (let i = parts.length; i > 0; i--) {
      const candidate = parts.slice(0, i).join("-").toLowerCase();
      const id = ids.find((known) => known.toLowerCase() === candidate);
      if (id) return id;
    }
    return null;
  };
  const base = (tag: string) => tag.split("-")[0].toLowerCase();

  const picked: string[] = [];
  for (const locale of locales) {
    if (!locale.trim()) continue;
    const id = match(locale);
    if (id && !picked.includes(id)) picked.push(id);
  }
  if (uiLocale?.trim() && !picked.some((id) => base(id) === base(uiLocale))) {
    const id = match(uiLocale);
    if (id) picked.push(id);
  }
  return picked;
}

/**
 * A dictionary's size, in the units it actually lands in: the catalog runs from
 * a few tens of KB to tens of MB, and rounding the small ones to "0.0 MB" would
 * hide the difference that matters when choosing one.
 */
export function formatDictionarySize(bytes: number, locale: string): string {
  const kb = bytes / 1000;
  if (kb < 1000) {
    return `${new Intl.NumberFormat(locale, { maximumFractionDigits: 0 }).format(kb)} KB`;
  }
  const mb = new Intl.NumberFormat(locale, {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  }).format(bytes / 1_000_000);
  return `${mb} MB`;
}
