/**
 * GENERATOR (not a real test) — run with `npx vitest run src/data/__gen__`.
 *
 * KaTeX's `symbols.ts` has only type imports, so importing it executes its
 * `defineSymbol` calls and yields the full LaTeX-command → (font, group,
 * codepoint) table. We normalize that into our own vendored `src/data/symbols.ts`
 * so the runtime never depends on KaTeX. Re-run when bumping the katex devDep.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, it } from "vitest";

// Resolves via katex's "./*" exports entry — only type imports, no runtime deps.
import katexSymbols from "katex/src/symbols.ts";

type KatexInfo = {
  font: string;
  group: string;
  replace: string | null | undefined;
};

// Normalize KaTeX group tokens to our compact set.
const GROUP_MAP: Record<string, string> = {
  mathord: "mathord",
  textord: "textord",
  bin: "bin",
  rel: "rel",
  open: "open",
  close: "close",
  punct: "punct",
  inner: "inner",
  "op-token": "op",
  "accent-token": "accent",
  spacing: "spacing",
};

function build(mode: "math" | "text"): string {
  const table = katexSymbols[mode] as Record<string, KatexInfo>;
  const lines: string[] = [];
  for (const name of Object.keys(table).sort()) {
    const { font, group, replace } = table[name];
    const g = GROUP_MAP[group];
    if (!g) throw new Error(`unknown group ${group} for ${name}`);
    if (font !== "main" && font !== "ams") {
      throw new Error(`unexpected font ${font} for ${name}`);
    }
    // `replace` is the codepoint string actually drawn; fall back to the name
    // for single-char entries that have no replacement.
    const ch = replace ?? name;
    lines.push(
      `  ${JSON.stringify(name)}: { font: ${JSON.stringify(font)}, ` +
        `group: ${JSON.stringify(g)}, char: ${JSON.stringify(ch)} },`,
    );
  }
  return lines.join("\n");
}

describe("generate vendored symbols", () => {
  it("writes src/data/symbols.ts", () => {
    const out = `/**
 * Vendored from KaTeX (MIT) — see KATEX_LICENSE. GENERATED by
 * src/data/__gen__/generate.test.ts; do not edit by hand.
 *
 * Maps a LaTeX command (or literal char) to the glyph we draw: which symbol
 * font it lives in, its atom group (drives spacing), and the actual character
 * (codepoint) to render. Font resolution to a concrete face happens at layout
 * time (mathord → Math-Italic; others → Main/AMS by \`font\`).
 */
export type SymGroup =
  | "mathord"
  | "textord"
  | "bin"
  | "rel"
  | "open"
  | "close"
  | "punct"
  | "inner"
  | "op"
  | "accent"
  | "spacing";

export type SymFont = "main" | "ams";

export interface SymbolInfo {
  readonly font: SymFont;
  readonly group: SymGroup;
  readonly char: string;
}

export const mathSymbols: Record<string, SymbolInfo> = {
${build("math")}
};

export const textSymbols: Record<string, SymbolInfo> = {
${build("text")}
};
`;
    const target = fileURLToPath(new URL("../symbols.ts", import.meta.url));
    writeFileSync(target, out);
    console.log(`wrote ${target}`);
  });
});
