export const DOUBLE_CLICK_TIME = 500;
export const CLICK_DISTANCE_THRESHOLD = 5;
export const TAP_DISTANCE_THRESHOLD = 30;
export const LONG_PRESS_DURATION = 400;
export const MOVEMENT_THRESHOLD = 10;
export const TAP_MAX_DURATION = 500;
export const EDGE_SCROLL_THRESHOLD = 80;
export const EDGE_SCROLL_SPEED = 12;
export const EDGE_SCROLL_MAX_SPEED = 120;
export const EDGE_SCROLL_ACCELERATION_RATE = 2.5;
export const CONTEXT_MENU_DURATION = 600;
export const IMAGE_DEFAULT_HEIGHT = 220;
export const SCROLLBAR_HOLD_DURATION = 150; // Shorter than long press, iOS feels snappy
export const SCROLLBAR_TOUCH_BUFFER = 16; // Pixels of buffer area around the thumb for touch detection
export const SELECTION_HANDLE_TOUCH_TARGET = 44; // Touch target size for selection handles (iOS HIG minimum)
export const CURSOR_DRAG_ACTIVATION_DELAY = 200; // ms before cursor drag activates (shorter than context menu)
export const CURSOR_TOUCH_RADIUS = 30; // px proximity to cursor to trigger drag mode
export const MAGNIFIER_WIDTH = 168;
export const MAGNIFIER_HEIGHT = 72;
export const MAGNIFIER_POINTER_SIZE = 10; // triangle pointer at bottom
export const MAGNIFIER_MIN_OFFSET_Y = 44; // minimum gap above touch point (fallback when no radius)

