// DO NOT EDIT. Generated by apps/web/scripts/gen-desktop-strings.mjs from
// apps/web/public/app/locales/<lng>/translation.json.
// Run `npm run gen:desktop-strings` in apps/web.

export const LOCALES = ["en"] as const;

export type Locale = (typeof LOCALES)[number];

export type StringKey = "menu.view" | "menu.showInspector" | "menu.showTasfer" | "menu.quit";

/** Per-key fallback locale, matching i18next's `fallbackLng`. */
export const FALLBACK_LOCALE: Locale = "en";

export const STRINGS: Record<Locale, Record<StringKey, string>> = {
  "en": {
    "menu.view": "View",
    "menu.showInspector": "Show Tasfer Inspector",
    "menu.showTasfer": "Show Tasfer",
    "menu.quit": "Quit",
  },
};
